# This is a basic workflow to help you get started with Actions
name: Public Ranking

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    environment: Score
    steps:
      # action
      - name: Reader Board Update
        id: hello
        uses: hankyul2/reader_board_action@v3.5
        env:
          API_TOKEN_GITHUB: ${{ secrets.pat }}
        with:
          public_repo: ajou_2021_spring_ai
          public_name: jbrbot
          public_author: colabforever123@gmail.com
          private_repo: ${{ secrets.repo }}
          private_name: ${{ secrets.name }}
          private_author: ${{ secrets.author }}
